#!/bin/bash

SEC=$(duration "$1")
shift
DESC="$@"

ansi # print blank line

while [[ $SEC -gt 0 ]]; do
    FMT_SEC=$(/bin/date -ju -f "%s" "$SEC" "+%M:%S")
    ansi --hide-cursor --no-restore -n --up=1 --column=1 --magenta "$FMT_SEC"
    ansi --hide-cursor --yellow " $DESC"
    SEC=$(( SEC - 1 ))
    sleep 1
done

ansi --hide-cursor --no-restore -n --up=1 --column=1 --cyan "00:00"
ansi --hide-cursor --cyan " $DESC"

